---
meta:
  passwords:
    postgres: (( param "specify postgres password" ))
    mbus: (( param "specify mbus password" ))
    vcap: (( param "specify vcap password" ))

name: master-bosh

releases:
- name: bosh
  url: (( grab $RELEASES_BOSH_URL ))
  sha1: (( grab $RELEASES_BOSH_SHA1 ))
- name: bosh-aws-cpi
  url: (( grab $RELEASES_BOSH_AWS_CPI_URL ))
  sha1: (( grab $RELEASES_BOSH_AWS_CPI_SHA1 ))

resource_pools:
- name: vms
  network: private
  env:
    bosh:
      password: (( grab meta.passwords.vcap ))
  stemcell:
    url: (( grab $STEMCELL_URL ))
    sha1: (( grab $STEMCELL_SHA1 ))
  cloud_properties:
    instance_type: m3.large
    iam_instance_profile: (( grab terraform_outputs.master_bosh_profile ))
    ephemeral_disk:
      size: 25_000
      type: gp2
      encrypted: true
    availability_zone: (( grab terraform_outputs.az1 ))

disk_pools:
- name: bosh-ssd
  disk_size: 20_000
  cloud_properties:
    type: gp2
    encrypted: true

networks:
- name: private
  type: manual
  subnets:
  - range: (( grab terraform_outputs.private_subnet_az1_cidr ))
    gateway: (( grab terraform_outputs.private_subnet_az1_gateway ))
    dns:
    - (( grab terraform_outputs.master_bosh_static_ip ))
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      subnet: (( grab terraform_outputs.private_subnet_az1 ))

instance_groups:
- name: bosh
  instances: 1
  resource_pool: vms
  persistent_disk_pool: bosh-ssd

  networks:
  - name: private
    default: [dns, gateway]
    static_ips:
    - (( grab terraform_outputs.master_bosh_static_ip ))

  jobs:
  - name: nats
    release: bosh
    properties:
      nats:
        allow_legacy_agents: false
        address: 127.0.0.1
        tls:
          ca: (( grab secrets.ca_cert ))
          client_ca:
            certificate: (( grab secrets.ca_cert ))
            private_key: (( grab secrets.ca_key ))
          server:
            certificate: (( grab secrets.bosh_nats_server_cert ))
            private_key: (( grab secrets.bosh_nats_server_key ))
          director:
            certificate: (( grab secrets.bosh_nats_director_cert ))
            private_key: (( grab secrets.bosh_nats_director_key ))
          health_monitor:
            certificate: (( grab secrets.bosh_nats_hm_cert ))
            private_key: (( grab secrets.bosh_nats_hm_key ))

  - name: powerdns
    release: bosh
    properties:
      dns:
        address: (( grab terraform_outputs.master_bosh_static_ip ))
        recursor: (( grab terraform_outputs.vpc_cidr_dns ))
        domain_name: masterbosh
        db: (( grab instance_groups.bosh.jobs.[postgres-9.4].properties.postgres ))

  - name: postgres-9.4
    release: bosh
    properties:
      postgres:
        listen_address: 127.0.0.1
        host: 127.0.0.1
        user: postgres
        password: (( grab meta.passwords.postgres ))
        database: bosh
        adapter: postgres

  - name: blobstore
    release: bosh
    properties:
      blobstore:
        address: (( grab terraform_outputs.master_bosh_static_ip ))
        port: 25250
        provider: dav
        director:
          user: director
          password: (( grab secrets.bosh_director_password ))
        agent:
          user: agent
          password: (( grab secrets.bosh_agent_password ))

  - name: director
    release: bosh
    properties:
      director:
        address: 127.0.0.1
        name: master-bosh
        db: (( grab instance_groups.bosh.jobs.[postgres-9.4].properties.postgres ))
        ssl:
          cert: (( grab secrets.bosh_director_cert ))
          key: (( grab secrets.bosh_director_key ))
        cpi_job: aws_cpi
        max_threads: 10
        user_management:
          provider: local
          local:
            users:
            - name: admin
              password: (( grab secrets.bosh_admin_password ))
            - name: hm
              password: (( grab secrets.bosh_hm_password ))
      nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
      blobstore: (( grab instance_groups.bosh.jobs.blobstore.properties.blobstore ))
      dns: (( grab instance_groups.bosh.jobs.powerdns.properties.dns ))
      ntp: [time.nist.gov]

  - name: health_monitor
    release: bosh
    properties:
      hm:
        director_account:
          user: hm
          password: (( grab secrets.bosh_hm_password ))
        resurrector_enabled: true
      nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
      director:
        address: 127.0.0.1

  - name: registry
    release: bosh
    properties:
      registry:
        address: (( grab terraform_outputs.master_bosh_static_ip ))
        host: (( grab terraform_outputs.master_bosh_static_ip ))
        db: (( grab instance_groups.bosh.jobs.[postgres-9.4].properties.postgres ))
        http:
          user: admin
          password: (( grab secrets.bosh_admin_password ))
          port: 25777
        username: admin
        password: (( grab secrets.bosh_admin_password ))
        port: 25777
        cloud:
          plugin: aws
          credentials_source: env_or_profile
          region: (( grab terraform_outputs.vpc_region ))

  - name: aws_cpi
    release: bosh-aws-cpi
    properties:
      aws:
        credentials_source: env_or_profile
        default_key_name: (( grab secrets.ca_public_key_name ))
        default_security_groups:
        - (( grab terraform_outputs.bosh_security_group ))
        default_iam_instance_profile: (( grab terraform_outputs.default_profile ))
        region: (( grab terraform_outputs.vpc_region ))
        encrypted: true
      registry: (( grab instance_groups.bosh.jobs.registry.properties.registry ))
      agent:
        mbus: (( concat "nats://" terraform_outputs.master_bosh_static_ip ":4222" ))
      nats: (( grab instance_groups.bosh.jobs.nats.properties.nats ))
      blobstore: (( grab instance_groups.bosh.jobs.blobstore.properties.blobstore ))

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}
  ssh_tunnel:
    host: (( grab terraform_outputs.master_bosh_static_ip ))
    port: 22
    user: vcap
    private_key: ./decrypt/master-bosh.pem
  mbus: (( concat "https://mbus:" meta.passwords.mbus "@" terraform_outputs.master_bosh_static_ip ":6868" ))
  properties:
    aws: (( grab instance_groups.bosh.jobs.aws_cpi.properties.aws ))
    agent:
      mbus: (( concat "https://mbus:" meta.passwords.mbus "@0.0.0.0:6868" ))
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: (( grab instance_groups.bosh.jobs.director.properties.ntp ))
