- type: replace
  path: /update?
  value:
    canaries: 1
    canary_watch_time: 3000-180000
    update_watch_time: 3000-180000
    max_in_flight: 4

- type: remove
  path: /cloud_provider

- type: remove
  path: /resource_pools

- type: remove
  path: /disk_pools

- type: remove
  path: /networks

- type: remove
  path: /instance_groups/name=bosh/resource_pool

- type: remove
  path: /instance_groups/name=bosh/persistent_disk_pool

- type: replace
  path: /instance_groups/name=bosh/vm_type?
  value: ((instance_type))

- type: replace
  path: /instance_groups/name=bosh/vm_extensions?
  value: [((instance_profile))]

- type: replace
  path: /instance_groups/name=bosh/persistent_disk_type?
  value: bosh

- type: replace
  path: /instance_groups/name=bosh/networks
  value:
  - name: ((network))
    static_ips: [((internal_ip))]

- type: replace
  path: /instance_groups/name=bosh/azs?
  value: [z1]

- type: remove
  path: /variables/name=mbus_bootstrap_password

- type: remove
  path: /variables/name=mbus_bootstrap_ssl

- type: replace
  path: /stemcells?
  value:
  - alias: default
    os: ubuntu-jammy
    version: latest

- type: replace
  path: /instance_groups/name=bosh/stemcell?
  value: default
