---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- {name: bosh-config}
- {name: ca-cert-store}
- {name: terraform-yaml}
- {name: terraform-yaml-development}
- {name: terraform-yaml-staging}
- {name: terraform-yaml-production}


run:
  path: bosh-config/ci/update-cloud-config-tooling.sh
