---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: 18fgsa/concourse-task

inputs:
- {name: bosh-config}
- {name: bosh-deployment}
- {name: certificate}
- {name: terraform-yaml}
- {name: common}
- {name: cg-s3-fisma-release, path: releases/fisma}
- {name: cg-s3-tripwire-release, path: releases/tripwire}
- {name: cg-s3-awslogs-release, path: releases/awslogs}
- {name: cg-s3-nessus-agent-release, path: releases/nessus-agent}
- {name: cg-s3-clamav-release, path: releases/clamav}
- {name: cg-s3-snort-release, path: releases/snort}
- {name: node-exporter-release, path: releases/node-exporter}
- {name: syslog-release, path: releases/syslog}

run:
  path: bosh-config/ci/update-runtime-config.sh

params:
  BOSH_CA_CERT:
  BOSH_ENVIRONMENT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
