vm_types:
- name: bosh
  cloud_properties:
    instance_type: m3.large
- name: nessus-manager
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      size: 30000
      type: gp2
      encrypted: true
- &prometheus-vm
  name: staging-prometheus
  cloud_properties:
    instance_type: m4.large
- name: production-prometheus
  cloud_properties:
    instance_type: m4.xlarge
- &concourse-web-vm
  name: staging-concourse-web
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      type: gp2
      size: 45000
      encrypted: true
- &concourse-worker-vm
  name: staging-concourse-worker
  cloud_properties:
    instance_type: m3.xlarge
    ephemeral_disk:
      type: gp2
      size: 300000
      encrypted: true
- &concourse-iaas-worker-vm
  name: staging-concourse-iaas-worker
  cloud_properties:
    instance_type: m4.large
    ephemeral_disk:
      type: gp2
      size: 300000
      encrypted: true
- <<: *concourse-web-vm
  name: production-concourse-web
- <<: *concourse-worker-vm
  name: production-concourse-worker
- <<: *concourse-iaas-worker-vm
  name: production-concourse-iaas-worker
- &monitoring-riemann-vm
  name: staging-monitoring-riemann
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk:
      type: gp2
      size: 30000
      encrypted: true
- &monitoring-influxdb-vm
  name: staging-monitoring-influxdb
  cloud_properties:
    instance_type: r4.xlarge
    ephemeral_disk:
      type: gp2
      size: 30000
      encrypted: true
- <<: *monitoring-riemann-vm
  name: production-monitoring-riemann
- <<: *monitoring-influxdb-vm
  name: production-monitoring-influxdb

networks:
- name: nessus-manager
  type: manual
  subnets:
  - range: (( grab terraform_outputs.private_subnet_az1_cidr ))
    reserved: (( grab terraform_outputs.private_subnet_az1_reserved ))
    gateway: (( grab terraform_outputs.private_subnet_az1_gateway ))
    static:
    - (( grab terraform_outputs.nessus_static_ip ))
    az: z1
    dns:
    - (( grab terraform_outputs.tooling_bosh_static_ip ))
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.nessus_security_group ))
      subnet: (( grab terraform_outputs.private_subnet_az1 ))
- name: staging-concourse
  type: manual
  subnets:
  - range: (( grab terraform_outputs.staging_concourse_subnet_cidr ))
    gateway: (( grab terraform_outputs.staging_concourse_subnet_gateway ))
    reserved:
    - (( grab terraform_outputs.staging_concourse_subnet_reserved ))
    az: z2
    dns:
    - (( grab terraform_outputs.tooling_bosh_static_ip ))
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      subnet: (( grab terraform_outputs.staging_concourse_subnet ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.staging_concourse_security_group ))
- name: production-concourse
  type: manual
  subnets:
  - range: (( grab terraform_outputs.production_concourse_subnet_cidr ))
    gateway: (( grab terraform_outputs.production_concourse_subnet_gateway ))
    reserved:
    - (( grab terraform_outputs.production_concourse_subnet_reserved ))
    az: z1
    dns:
    - (( grab terraform_outputs.tooling_bosh_static_ip ))
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      subnet: (( grab terraform_outputs.production_concourse_subnet ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.production_concourse_security_group ))
- name: staging-monitoring
  type: manual
  subnets:
  - range: (( grab terraform_outputs.staging_monitoring_subnet_cidr ))
    gateway: (( grab terraform_outputs.staging_monitoring_subnet_gateway ))
    reserved:
    - (( grab terraform_outputs.staging_monitoring_subnet_reserved ))
    static:
    - (( grab terraform_outputs.staging_monitoring_riemann_address ))
    - (( grab terraform_outputs.staging_monitoring_influxdb_address ))
    az: z2
    dns:
    - (( grab terraform_outputs.tooling_bosh_static_ip ))
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      subnet: (( grab terraform_outputs.staging_monitoring_subnet ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.staging_monitoring_security_group ))
- name: production-monitoring
  type: manual
  subnets:
  - range: (( grab terraform_outputs.production_monitoring_subnet_cidr ))
    gateway: (( grab terraform_outputs.production_monitoring_subnet_gateway ))
    reserved:
    - (( grab terraform_outputs.production_monitoring_subnet_reserved ))
    static:
    - (( grab terraform_outputs.production_monitoring_riemann_address ))
    - (( grab terraform_outputs.production_monitoring_influxdb_address ))
    az: z1
    dns:
    - (( grab terraform_outputs.tooling_bosh_static_ip ))
    - (( grab terraform_outputs.vpc_cidr_dns ))
    cloud_properties:
      subnet: (( grab terraform_outputs.production_monitoring_subnet ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
      - (( grab terraform_outputs.production_monitoring_security_group ))

vm_extensions:
- name: nessus-manager-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.nessus_elb_name ))
- name: staging-prometheus-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.staging_prometheus_elb_name ))
- name: production-prometheus-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.production_prometheus_elb_name ))
- name: staging-concourse-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.staging_concourse_elb_name ))
- &concourse-profile
  name: staging-concourse-profile
  cloud_properties:
    iam_instance_profile: (( grab terraform_outputs.concourse_worker_profile ))
- &concourse-iaas-profile
  name: staging-concourse-iaas-profile
  cloud_properties:
    iam_instance_profile: (( grab terraform_outputs.concourse_iaas_worker_profile ))
- name: production-concourse-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.production_concourse_elb_name ))
- <<: *concourse-profile
  name: production-concourse-profile
- <<: *concourse-iaas-profile
  name: production-concourse-iaas-profile
- name: staging-monitoring-grafana-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.staging_monitoring_elb_name ))
- name: staging-monitoring-riemann-profile
  cloud_properties:
    iam_instance_profile: (( grab terraform_outputs.riemann_monitoring_profile ))
- name: production-monitoring-grafana-lb
  cloud_properties:
    elbs:
    - (( grab terraform_outputs.production_monitoring_elb_name ))
- name: production-monitoring-riemann-profile
  cloud_properties:
    iam_instance_profile: (( grab terraform_outputs.riemann_monitoring_profile ))

disk_types:
- name: bosh
  disk_size: 300000
- name: nessus-manager
  disk_size: 120000
  cloud_properties:
    type: gp2
    encrypted: true
- &prometheus-small-disk
  name: staging-prometheus-small
  disk_size: 2048
  cloud_properties:
    type: gp2
    encrypted: true
- &prometheus-large-disk
  name: staging-prometheus-large
  disk_size: 200_000
  cloud_properties:
    type: gp2
    encrypted: true
- <<: *prometheus-small-disk
  name: production-prometheus-small
- <<: *prometheus-large-disk
  name: production-prometheus-large
- &monitoring-riemann-disk
  name: staging-monitoring-riemann
  disk_size: 5000
  cloud_properties:
    type: gp2
    encrypted: true
- &monitoring-influxdb-disk
  name: staging-monitoring-influxdb
  disk_size: 50000
  cloud_properties:
    type: gp2
    encrypted: true
- <<: *monitoring-riemann-disk
  name: production-monitoring-riemann
- <<: *monitoring-influxdb-disk
  name: production-monitoring-influxdb

compilation:
  network: production-concourse
